import { Book } from '@/types/books';

export const INITIAL_BOOKS: Book[] = [
  // ==================== جونيور (Junior - الصف الأول الثانوي) ====================
  {
    id: 'jun-ar-t1',
    title: 'عربي جونيور ترمين',
    subject: 'عربي',
    stage: 'junior',
    term: 'term_1',
    price: 45,
    pdfUrl: '/books/junior_arabic.pdf',
    samplePdfUrl: '/books/junior_arabic.pdf',
    isActive: true,
  },
  {
    id: 'jun-mth-t1',
    title: 'ماث جونيور',
    subject: 'ماث',
    stage: 'junior',
    term: 'term_1',
    price: 40,
    pdfUrl: '/books/junior_math.pdf',
    samplePdfUrl: '/books/junior_math.pdf',
    isActive: true,
  },
  {
    id: 'jun-nat-t1',
    title: 'تربية وطنية جونيور ترمين',
    subject: 'تربية وطنية',
    stage: 'junior',
    term: 'term_1',
    price: 50,
    pdfUrl: '/books/junior_national_education.pdf',
    samplePdfUrl: '/books/junior_national_education.pdf',
    isActive: true,
  },
  {
    id: 'jun-rel-t1',
    title: 'دين جونيور',
    subject: 'دين',
    stage: 'junior',
    term: 'term_1',
    price: 30,
    pdfUrl: '/books/junior_religion.pdf',
    samplePdfUrl: '/books/junior_religion.pdf',
    isActive: true,
  },

  // ==================== ويلر (Wheeler - الصف الثاني الثانوي) ====================
  {
    id: 'whl-ar-t1',
    title: 'عربي ويلر ترمين',
    subject: 'عربي',
    stage: 'wheeler',
    term: 'term_1',
    price: 50,
    pdfUrl: '/books/wheeler_arabic.pdf',
    samplePdfUrl: '/books/wheeler_arabic.pdf',
    isActive: true,
  },
  {
    id: 'whl-mth-t1',
    title: 'ماث ويلر',
    subject: 'ماث',
    stage: 'wheeler',
    term: 'term_1',
    price: 45,
    pdfUrl: '/books/wheeler_math.pdf',
    samplePdfUrl: '/books/wheeler_math.pdf',
    isActive: true,
  },

  // ==================== سينيور (Senior - الصف الثالث الثانوي) ====================
  {
    id: 'sen-ar-t1',
    title: 'عربي سينيور',
    subject: 'عربي',
    stage: 'senior',
    term: 'term_1',
    price: 60,
    pdfUrl: '/books/senior_arabic.pdf',
    samplePdfUrl: '/books/senior_arabic.pdf',
    isActive: true,
  },
  {
    id: 'sen-eng-t1',
    title: 'انجلش سينيور',
    subject: 'إنجليزي',
    stage: 'senior',
    term: 'term_1',
    price: 55,
    pdfUrl: '/books/senior_english.pdf',
    samplePdfUrl: '/books/senior_english.pdf',
    isActive: true,
  },
  {
    id: 'sen-eval-t1',
    title: 'التقويمات الذاتية للمفاهيم الاساسية 2026',
    subject: 'مفاهيم أساسية',
    stage: 'senior',
    term: 'term_1',
    price: 5,
    pdfUrl: '/books/senior_evaluations_2026.pdf',
    samplePdfUrl: '/books/senior_evaluations_2026.pdf',
    isActive: true,
  },
  {
    id: 'sen-com-t1',
    title: 'المفاهيم الأساسية لبيئة التجارة الحديثة',
    subject: 'تجارة واقتصاد',
    stage: 'senior',
    term: 'term_1',
    price: 50,
    pdfUrl: '/books/senior_modern_commerce.pdf',
    samplePdfUrl: '/books/senior_modern_commerce.pdf',
    isActive: true,
  },
  {
    id: 'sen-mth-t1',
    title: 'ماث سينيور (قسم سوفت وير)',
    subject: 'ماث',
    stage: 'senior',
    term: 'term_1',
    price: 45,
    pdfUrl: '/books/senior_math_software.pdf',
    samplePdfUrl: '/books/senior_math_software.pdf',
    isActive: true,
  },
  {
    id: 'sen-mth-mt-t1',
    title: 'ماث سينيور (قسم مودرن تريد MT) - ترم أول',
    subject: 'ماث',
    stage: 'senior',
    term: 'term_1',
    price: 45,
    pdfUrl: '/books/senior_math_mt_t1.pdf',
    samplePdfUrl: '/books/senior_math_mt_t1.pdf',
    isActive: true,
  },
  {
    id: 'sen-mth-mt-t2',
    title: 'ماث سينيور (قسم مودرن تريد MT) - ترم ثاني',
    subject: 'ماث',
    stage: 'senior',
    term: 'term_2',
    price: 45,
    pdfUrl: '/books/senior_math_mt_t2.pdf',
    samplePdfUrl: '/books/senior_math_mt_t2.pdf',
    isActive: true,
  },
  {
    id: 'sen-mech-t1',
    title: 'ميكا سينيور',
    subject: 'ميكانيكا',
    stage: 'senior',
    term: 'term_1',
    price: 50,
    pdfUrl: '/books/senior_mechanics.pdf',
    samplePdfUrl: '/books/senior_mechanics.pdf',
    isActive: true,
  },
  {
    id: 'sen-phy-t1',
    title: 'فيزيكس سينيور ترم اول',
    subject: 'فيزياء',
    stage: 'senior',
    term: 'term_1',
    price: 25,
    pdfUrl: '/books/senior_physics_t1.pdf',
    samplePdfUrl: '/books/senior_physics_t1.pdf',
    isActive: true,
  },
  {
    id: 'sen-phy-t2',
    title: 'فيزيكس سينيور ترم ثاني',
    subject: 'فيزياء',
    stage: 'senior',
    term: 'term_2',
    price: 30,
    pdfUrl: '/books/senior_physics_t2.pdf',
    samplePdfUrl: '/books/senior_physics_t2.pdf',
    isActive: true,
  },
  {
    id: 'sen-rel-t1',
    title: 'دين سينيور',
    subject: 'دين',
    stage: 'senior',
    term: 'term_1',
    price: 70,
    pdfUrl: '/books/senior_religion.pdf',
    samplePdfUrl: '/books/senior_religion.pdf',
    isActive: true,
  },
  {
    id: 'sen-std-t1',
    title: 'دراسات سينيور (مستر عمرو)',
    subject: 'دراسات',
    stage: 'senior',
    term: 'term_1',
    price: 50,
    pdfUrl: '/books/senior_studies_amr.pdf',
    samplePdfUrl: '/books/senior_studies_amr.pdf',
    isActive: true,
  },
];
