import { Book } from '@/types/books';

export const SAMPLE_PDF_URL = "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf";

export const INITIAL_BOOKS: Book[] = [
  // ==================== جونيور (Junior) ====================
  {
    id: 'jun-eng-t1',
    title: 'كتاب الإنجليزي - ترم أول',
    subject: 'إنجليزي',
    stage: 'junior',
    term: 'term_1',
    price: 90,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'jun-eng-t2',
    title: 'كتاب الإنجليزي - ترم ثاني',
    subject: 'إنجليزي',
    stage: 'junior',
    term: 'term_2',
    price: 90,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'jun-mth-t1',
    title: 'كتاب الماث - ترم أول',
    subject: 'ماث',
    stage: 'junior',
    term: 'term_1',
    price: 95,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'jun-mth-t2',
    title: 'كتاب الماث - ترم ثاني',
    subject: 'ماث',
    stage: 'junior',
    term: 'term_2',
    price: 95,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'jun-phy-t1',
    title: 'كتاب الفيزياء - ترم أول',
    subject: 'فيزياء',
    stage: 'junior',
    term: 'term_1',
    price: 85,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'jun-phy-t2',
    title: 'كتاب الفيزياء - ترم ثاني',
    subject: 'فيزياء',
    stage: 'junior',
    term: 'term_2',
    price: 85,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'jun-chm-t1',
    title: 'كتاب الكيمياء - ترم أول',
    subject: 'كيمياء',
    stage: 'junior',
    term: 'term_1',
    price: 80,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'jun-chm-t2',
    title: 'كتاب الكيمياء - ترم ثاني',
    subject: 'كيمياء',
    stage: 'junior',
    term: 'term_2',
    price: 80,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'jun-bio-t1',
    title: 'كتاب الأحياء - ترم أول',
    subject: 'أحياء',
    stage: 'junior',
    term: 'term_1',
    price: 85,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'jun-bio-t2',
    title: 'كتاب الأحياء - ترم ثاني',
    subject: 'أحياء',
    stage: 'junior',
    term: 'term_2',
    price: 85,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'jun-arb-t1',
    title: 'كتاب العربي - ترم أول',
    subject: 'عربي',
    stage: 'junior',
    term: 'term_1',
    price: 100,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'jun-arb-t2',
    title: 'كتاب العربي - ترم ثاني',
    subject: 'عربي',
    stage: 'junior',
    term: 'term_2',
    price: 100,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },

  // ==================== ويلر (Wheeler) ====================
  {
    id: 'whl-eng-t1',
    title: 'كتاب الإنجليزي - ترم أول',
    subject: 'إنجليزي',
    stage: 'wheeler',
    term: 'term_1',
    price: 95,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'whl-eng-t2',
    title: 'كتاب الإنجليزي - ترم ثاني',
    subject: 'إنجليزي',
    stage: 'wheeler',
    term: 'term_2',
    price: 95,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'whl-mth-t1',
    title: 'كتاب الماث - ترم أول',
    subject: 'ماث',
    stage: 'wheeler',
    term: 'term_1',
    price: 105,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'whl-mth-t2',
    title: 'كتاب الماث - ترم ثاني',
    subject: 'ماث',
    stage: 'wheeler',
    term: 'term_2',
    price: 105,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'whl-phy-t1',
    title: 'كتاب الفيزياء - ترم أول',
    subject: 'فيزياء',
    stage: 'wheeler',
    term: 'term_1',
    price: 95,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'whl-phy-t2',
    title: 'كتاب الفيزياء - ترم ثاني',
    subject: 'فيزياء',
    stage: 'wheeler',
    term: 'term_2',
    price: 95,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'whl-chm-t1',
    title: 'كتاب الكيمياء - ترم أول',
    subject: 'كيمياء',
    stage: 'wheeler',
    term: 'term_1',
    price: 90,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'whl-chm-t2',
    title: 'كتاب الكيمياء - ترم ثاني',
    subject: 'كيمياء',
    stage: 'wheeler',
    term: 'term_2',
    price: 90,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'whl-bio-t1',
    title: 'كتاب الأحياء - ترم أول',
    subject: 'أحياء',
    stage: 'wheeler',
    term: 'term_1',
    price: 90,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'whl-bio-t2',
    title: 'كتاب الأحياء - ترم ثاني',
    subject: 'أحياء',
    stage: 'wheeler',
    term: 'term_2',
    price: 90,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'whl-arb-t1',
    title: 'كتاب العربي - ترم أول',
    subject: 'عربي',
    stage: 'wheeler',
    term: 'term_1',
    price: 110,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'whl-arb-t2',
    title: 'كتاب العربي - ترم ثاني',
    subject: 'عربي',
    stage: 'wheeler',
    term: 'term_2',
    price: 110,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },

  // ==================== سينيور (Senior) ====================
  {
    id: 'sen-phy-t1',
    title: 'كتاب الفيزياء - ترم أول',
    subject: 'فيزياء',
    stage: 'senior',
    term: 'term_1',
    price: 130,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'sen-phy-t2',
    title: 'كتاب الفيزياء - ترم ثاني',
    subject: 'فيزياء',
    stage: 'senior',
    term: 'term_2',
    price: 130,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'sen-chm-t1',
    title: 'كتاب الكيمياء - ترم أول',
    subject: 'كيمياء',
    stage: 'senior',
    term: 'term_1',
    price: 125,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'sen-chm-t2',
    title: 'كتاب الكيمياء - ترم ثاني',
    subject: 'كيمياء',
    stage: 'senior',
    term: 'term_2',
    price: 125,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'sen-mth-t1',
    title: 'كتاب الماث - ترم أول',
    subject: 'ماث',
    stage: 'senior',
    term: 'term_1',
    price: 135,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'sen-mth-t2',
    title: 'كتاب الماث - ترم ثاني',
    subject: 'ماث',
    stage: 'senior',
    term: 'term_2',
    price: 135,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'sen-bio-t1',
    title: 'كتاب الأحياء - ترم أول',
    subject: 'أحياء',
    stage: 'senior',
    term: 'term_1',
    price: 120,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'sen-bio-t2',
    title: 'كتاب الأحياء - ترم ثاني',
    subject: 'أحياء',
    stage: 'senior',
    term: 'term_2',
    price: 120,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'sen-geo-t1',
    title: 'كتاب الجيولوجيا - ترم أول',
    subject: 'جيولوجيا',
    stage: 'senior',
    term: 'term_1',
    price: 110,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'sen-geo-t2',
    title: 'كتاب الجيولوجيا - ترم ثاني',
    subject: 'جيولوجيا',
    stage: 'senior',
    term: 'term_2',
    price: 110,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'sen-arb-t1',
    title: 'كتاب العربي - ترم أول',
    subject: 'عربي',
    stage: 'senior',
    term: 'term_1',
    price: 140,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'sen-arb-t2',
    title: 'كتاب العربي - ترم ثاني',
    subject: 'عربي',
    stage: 'senior',
    term: 'term_2',
    price: 140,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'sen-eng-t1',
    title: 'كتاب الإنجليزي - ترم أول',
    subject: 'إنجليزي',
    stage: 'senior',
    term: 'term_1',
    price: 115,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
  {
    id: 'sen-eng-t2',
    title: 'كتاب الإنجليزي - ترم ثاني',
    subject: 'إنجليزي',
    stage: 'senior',
    term: 'term_2',
    price: 115,
    pdfUrl: SAMPLE_PDF_URL,
    isActive: true,
  },
];
